import { z } from "zod";
import { adminMutationError, adminReadError, requireAdminRead, writeAdminAudit } from "../../../../lib/admin";
import { db } from "../../../../lib/db";
import { jsonError, noStoreJson, parseJsonBody } from "../../../../lib/http";
import { assertSafeMutation } from "../../../../lib/security";
import { requireElevatedAdmin } from "../../../../lib/session";

export const runtime="nodejs";
export async function GET(request:Request){try{await requireAdminRead(request);const url=new URL(request.url);const severity=url.searchParams.get('severity')||'all';if(!['all','info','warning','critical'].includes(severity))return jsonError("فیلتر معتبر نیست.",400);const [events,audits,stats]=await Promise.all([
  db()<Array<{id:number;user_id:string|null;phone_masked:string|null;event_type:string;severity:string;details:unknown;created_at:string;resolved_at:string|null;resolution:string|null}>>`select e.id,e.user_id,case when u.id is null then null else concat(left(u.phone_e164,5),'•••',right(u.phone_e164,3)) end as phone_masked,e.event_type,e.severity,e.details,e.created_at,e.resolved_at,e.resolution from security_events e left join users u on u.id=e.user_id where (${severity}='all' or e.severity=${severity}) order by e.created_at desc limit 100`,
  db()<Array<{id:number;admin_phone:string;action:string;target_type:string|null;target_id:string|null;before_state:unknown;after_state:unknown;created_at:string}>>`select a.id,concat(left(u.phone_e164,5),'•••',right(u.phone_e164,3)) as admin_phone,a.action,a.target_type,a.target_id,a.before_state,a.after_state,a.created_at from admin_audit_logs a join users u on u.id=a.admin_user_id order by a.created_at desc limit 100`,
  db()<Array<{critical_open:string;warning_open:string;suspended:string;admin_sessions:string}>>`select (select count(*)::text from security_events where severity='critical' and resolved_at is null) critical_open,(select count(*)::text from security_events where severity='warning' and resolved_at is null) warning_open,(select count(*)::text from users where status='suspended') suspended,(select count(*)::text from sessions s join users u on u.id=s.user_id where u.role='admin' and s.revoked_at is null and s.expires_at>now()) admin_sessions`,
]);return noStoreJson({events,audits,stats:{criticalOpen:Number(stats[0].critical_open),warningOpen:Number(stats[0].warning_open),suspended:Number(stats[0].suspended),adminSessions:Number(stats[0].admin_sessions)}});}catch(error){return adminReadError(error);}}

export async function PATCH(request:Request){try{assertSafeMutation(request);const admin=await requireElevatedAdmin(request);const parsed=z.object({eventId:z.number().int().positive(),resolution:z.string().min(3).max(500)}).safeParse(await parseJsonBody(request,2_000));if(!parsed.success)return jsonError("نتیجه بررسی معتبر نیست.",400);const rows=await db()<Array<{id:number;resolved_at:string|null}>>`update security_events set resolved_at=now(),resolved_by=${admin.userId},resolution=${parsed.data.resolution} where id=${parsed.data.eventId} and resolved_at is null returning id,resolved_at`;if(!rows.length)return jsonError("رخداد باز پیدا نشد.",404);await writeAdminAudit({adminUserId:admin.userId,action:"security.resolve",request,targetType:"security_event",targetId:String(parsed.data.eventId),after:{resolution:parsed.data.resolution}});return noStoreJson({ok:true,event:rows[0]});}catch(error){return adminMutationError(error,"رخداد امنیتی به‌روزرسانی نشد.");}}
